parameters: {}
environment:
  DIGITALOCEAN_ACCESS_TOKEN: ${DIGITALOCEAN_ACCESS_TOKEN}
packages:
    - name: do-management
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: stop-droplets
          binary: false
          main: ""
          runtime: go:1.20
          web: true
          webSecure: false
          parameters: {}
          environment: {}
          annotations: {}
          limits:
            timeout: 30000
